### ISSUE TITLE
[query] How can I programatically add a choice after a ChoicesEnum class is defined?

### ISSUE THREAD

**Issue by kwill** [loggi/python-choicesenum#12]
* Choices Enum version: 0.2.2
* Python version: 3.5.4
* Operating System: Debian 9

### Description

I have defined a ChoicesEnum class as follows:

    class Fruit(ChoicesEnum):
        UNDEFINED = 0, "Undefined"
        APPLE = 1, "Apple"
        BANANA = 2, "Banana"

And a Django model as follows:

    class Order(models.Model):
        user = models.ForeignKey(settings.AUTH_USER_MODEL)
        fruit = EnumIntegerField(enum=Fruit, default=Fruit.UNDEFINED)
        volume_total = models.DecimalField(default=0, decimal_places=2, max_digits=6)

I want to programatically add fruit to the list when the Django site starts up, so that individual instances can have different fruit lists. For example, on server A I want to add `CUCUMBER = 3, "Cucumber"` as a choice. How can I do this?

I thought of defining NewFruit, a class derived from of Fruit, but then I'd have to define NewOrder too (so that I can override the `fruit` field entry). Can I instead manipulate Fruit itself?

**Comment by fgmacedo** [comment]
Hi @kwill, 

The `ChoicesEnum` inherits from from the `Enum` from the standard library, that is _immutable_. So _afaik_, this is not possible.

Even [extending an `Enum` class that already define members is not possible](https://docs.python.org/3/library/enum.html#restricted-subclassing-of-enumerations).

You can create an dynamic `Enum` from scratch using this, but I don't know if this solves your problem:

``` python
In [1]: from choicesenum import ChoicesEnum
In [2]: Colors = ChoicesEnum('Colors', {'red': '#f00', 'green': '#0f0'})
In [3]: Colors.red
Out[3]: Colors('#f00').red
```

**Comment by kwill** [comment]
That answers my question, thanks!
