### ISSUE TITLE
Please do a release with Django 2.0 support

### ISSUE THREAD

**Issue by si14** [loggi/python-choicesenum#13]
It would be great to have a 2.0-compatible version in PyPI!

**Comment by fgmacedo** [comment]
Hi @si14, thanks for your message.

Actually, the published version already support Django 2.0.

The PR that mention Django 2.0 support just adds the 2.0 version under the automated tests matrix: https://github.com/loggi/python-choicesenum/pull/11/files

But yes, I forgot to update the readme to mention this.

Best regards!

**Comment by fgmacedo** [comment]
Closed in https://github.com/loggi/python-choicesenum/releases/tag/v0.3.0

**Comment by si14** [comment]
Cheers!
