### ISSUE TITLE
Not compatible with django 3

### ISSUE THREAD

**Issue by K0Te** [loggi/python-choicesenum#227]
Hi,

* Choices Enum version: 0.6.0
* Python version: 3.7
* Operating System:

### Description

According to https://docs.djangoproject.com/en/3.0/releases/3.0/ :
`django.utils.six - Remove usage of this vendored library or switch to six.`

Latest `0.6.0` fails with django 3 with following error:
```
    from choicesenum.django.fields import (
  File "/usr/local/lib/python3.7/site-packages/choicesenum/django/fields.py", line 8, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.7/site-packages/django/utils/__init__.py)
```

**Comment by fgmacedo** [comment]
Hi @K0Te , thanks for reporting this.

**Comment by leandrolerena** [comment]
you can use six for a quick fix https://pypi.org/project/six/ 
and replace 

`import six from django utils`
thorugh

`import six`

**Comment by fgmacedo** [comment]
Closed by https://github.com/loggi/python-choicesenum/pull/231.
