### ISSUE TITLE
ChoicesEnum isn't hashable

### ISSUE THREAD

**Issue by jodal** [loggi/python-choicesenum#4]
* Choices Enum version: 0.1.6
* Python version: 3.6.2
* Operating System: Linux

### Description

I'm porting existing Django code to use choicesenum. One existing use case that doesn't work is to use enum values as keys in a dict, because ChoicesEnum isn't hashable, like the stdlib enum implementation is.

### What I Did

``` python
>>> from enum import Enum, IntEnum
>>> from choicesenum import ChoicesEnum
>>> class Foo(Enum):
...     A = 1
...     B = 2
...     C = 3
...
>>> class Bar(IntEnum):
...     A = 1
...     B = 2
...     C = 3
...
>>> class Baz(ChoicesEnum):
...     A = 1
...     B = 2
...     C = 3
...
>>> Foo(1)
<Foo.A: 1>
>>> hash(Foo(1))
-8133611313320584089
>>> Bar(1)
<Bar.A: 1>
>>> hash(Bar(1))
1
>>> Baz(1)
Baz(1).A
>>> hash(Baz(1))                                                                                         
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'Baz'
```

**Comment by jodal** [comment]
This also makes it impossible to create a set of enum values, as that also requires the value to be hashable.

**Comment by fgmacedo** [comment]
Thanks @jodal for reporting this issue. I'll release a fix ASAP.

**Comment by jodal** [comment]
Awesome! Thanks for the quick turnaround :-)
