### ISSUE TITLE
ChoicesEnum with integers not comparable with itself or int

### ISSUE THREAD

**Issue by jodal** [loggi/python-choicesenum#6]
* Choices Enum version: 0.1.7
* Python version: 3.6.2
* Operating System: Linux

## Description

I'm porting existing Django code to use choiceenum. In this code, there is two use cases that causes comparision of the `choicesenum.django.fields.EnumIntegerField` values:

- Sorting in Python instead of the DB (comparing `EnumIntegerField` to `EnumIntegerField`)
- Running `.full_clean()` on the model, causing comparision between the `ChoicesEnum` type and `-2**31`, which is probably the lowest value that can be stored in the database field used by `EnumIntegerField` when running on PostgreSQL.

### Data model

``` python
from choicesenum import ChoicesEnum
from choicesenum.django.fields import EnumIntegerField

from django.db import models


class ProductNumber(ChoicesEnum):
    UNDEFINED = None
    COKE = 10
    HOT_DOG = 20

class Product(models.Model):
    product_number = EnumIntegerField(
        enum=ProductNumber,
        default=ProductNumber.UNDEFINED,
        unique=True,
        null=True)
   # ... other irrelevant fields ...
```

### Example: Sorting in Python

``` python
items = sorted(items, key=lambda item: (item.start_date, item.product.product_number)
```

This would cause an error like this:

```
TypeError: '<' not supported between instances of 'ProductNumber' and 'ProductNumber'
```

### Example: Model validation through `full_clean()`

```
product.full_clean()
```

This would cause an error like this raised from `django/core/validators.py:325`:

```
TypeError: '<' not supported between instances of 'ProductNumber' and 'int'
```

### Possible solution: subclass int

My first attempt at resolving this was to subclass int, like `IntEnum`:

``` python
class ProductNumber(int, ChoicesEnum):
    UNDEFINED = 0
    COKE = 10
    HOT_DOG = 20
```

Though, this immediately crashed with:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/enum.py", line 199, in __new__
    enum_member = __new__(enum_class, *args)
  File ".../lib/python3.6/site-packages/choicesenum/enums.py", line 10, in__new__
    obj = object.__new__(cls)
TypeError: object.__new__(ProductNumber) is not safe, use ProductNumber.__new__()
```

**Comment by fgmacedo** [comment]
Thanks @jodal. I've implemented the [rich comparison methods](https://docs.python.org/3.6/reference/datamodel.html#object.__lt__).

**Comment by jodal** [comment]
Lovely! :-D
